name: Continuous integration for Android

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .Net 7
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.x.x'
      
      - name: Restore dependencies
        run: |
          dotnet tool install -g Redth.Net.Maui.Check
          cd src/Asv.Drones.Gui.Android
          maui-check --fix --non-interactive --ci
          dotnet workload install android
          dotnet workload restore
          dotnet restore

      - name: Build application
        run: |
          cd src/Asv.Drones.Gui.Android
          dotnet build -c Release --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: ${{ github.workspace }}/src/Asv.Drones.Gui.Android/bin/Release/net7.0-android/
          if-no-files-found: error

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-release
          path: windows